USE ivolunteer;

CREATE TABLE LOCATION (
    ID VARCHAR(36) NOT NULL,
    STREET VARCHAR(256),
    CITY VARCHAR(256),
    STATE VARCHAR(2),
    ZIP VARCHAR(16),
    LOCATION VARCHAR(512),
    LATITUDE VARCHAR(128),
    LONGITUDE VARCHAR(128),
    PRIMARY KEY (ID)
);

SELECT AddGeometryColumn( 'public', 'location', 'geom', 4326, 'POINT', 2 );

CREATE TABLE TIMESTAMP (
    ID VARCHAR(36) NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE EVENT (
    ID VARCHAR(36) NOT NULL,
    TITLE VARCHAR(256) NOT NULL,
    DESCRIPTION VARCHAR(16384) NOT NULL,
    DURATION NUMERIC(16),
    CONTACT VARCHAR(256),
    URL VARCHAR(256),
    PHONE VARCHAR(64),
    EMAIL VARCHAR(256),
    SOURCE_ID VARCHAR(36),
    SOURCE_KEY VARCHAR(128),
    SOURCE_URL VARCHAR(256),
    PRIMARY KEY (ID)
);

CREATE TABLE EVENT_TIMESTAMP (
    TIMESTAMP_ID VARCHAR(36) NOT NULL,
    EVENT_ID VARCHAR(36) NOT NULL
);

ALTER TABLE EVENT_TIMESTAMP ADD CONSTRAINT ET_EVENT_FK FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID);
ALTER TABLE EVENT_TIMESTAMP ADD CONSTRAINT ET_TIMESTAMP_FK FOREIGN KEY (TIMESTAMP_ID) REFERENCES TIMESTAMP(ID);

CREATE TABLE ORGANIZATION (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    DESCRIPTION VARCHAR(8192),
    PHONE VARCHAR(64),
    EMAIL VARCHAR(512),
    URL VARCHAR(256),
    ORGANIZATION_TYPE_ID VARCHAR(36),
    SOURCE_ID VARCHAR(36),
    SOURCE_KEY VARCHAR(128),
    SOURCE_URL VARCHAR(256),
    PRIMARY KEY (ID)
);

CREATE TABLE ORGANIZATION_TYPE (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(128),
    PRIMARY KEY (ID)
);

ALTER TABLE ORGANIZATION ADD CONSTRAINT ORGANIZATION_TYPE_FK FOREIGN KEY (ORGANIZATION_TYPE_ID) REFERENCES ORGANIZATION_TYPE(ID);

CREATE TABLE EVENT_ORGANIZATION (
    EVENT_ID VARCHAR(36) NOT NULL,
    ORGANIZATION_ID VARCHAR(36) NOT NULL
);

ALTER TABLE EVENT_ORGANIZATION ADD CONSTRAINT EO_ORGANIZATIONS_FK FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ID);
ALTER TABLE EVENT_ORGANIZATION ADD CONSTRAINT EO_EVENTS_FK FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID);

CREATE TABLE EVENT_LOCATION (
    EVENT_ID VARCHAR(36) NOT NULL,
    LOCATION_ID VARCHAR(36) NOT NULL
);

ALTER TABLE EVENT_LOCATION ADD CONSTRAINT EL_EVENT_FK FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID);
ALTER TABLE EVENT_LOCATION ADD CONSTRAINT EL_LOCATION_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(ID);

CREATE TABLE ORGANIZATION_LOCATION (
    ORGANIZATION_ID VARCHAR(36) NOT NULL,
    LOCATION_ID VARCHAR(36) NOT NULL
);

ALTER TABLE ORGANIZATION_LOCATION ADD CONSTRAINT OL_ORGANIZATIONS_FK FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ID);
ALTER TABLE ORGANIZATION_LOCATION ADD CONSTRAINT OL_LOCATION_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(ID);

CREATE TABLE INTEREST_AREA (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE EVENT_INTEREST_AREA (
    INTEREST_AREA_ID VARCHAR(36) NOT NULL,
    EVENT_ID VARCHAR(36) NOT NULL
);

ALTER TABLE EVENT_INTEREST_AREA ADD CONSTRAINT EIA_INTEREST_AREA_FK FOREIGN KEY (INTEREST_AREA_ID) REFERENCES INTEREST_AREA(ID);
ALTER TABLE EVENT_INTEREST_AREA ADD CONSTRAINT EIA_EVENTS_FK FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID);

CREATE TABLE ORGANIZATION_INTEREST_AREA (
    INTEREST_AREA_ID VARCHAR(36) NOT NULL,
    ORGANIZATION_ID VARCHAR(36) NOT NULL
);

ALTER TABLE ORGANIZATION_INTEREST_AREA ADD CONSTRAINT OIA_INTEREST_AREA_FK FOREIGN KEY (INTEREST_AREA_ID) REFERENCES INTEREST_AREA(ID);
ALTER TABLE ORGANIZATION_INTEREST_AREA ADD CONSTRAINT OIA_EVENTS_FK FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ID);

CREATE TABLE SOURCE (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(128),
    ETL_CLASS VARCHAR(128),
    URL VARCHAR(512),
    PRIMARY KEY (ID)
);

ALTER TABLE EVENT ADD CONSTRAINT EVENTS_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE(ID);
ALTER TABLE ORGANIZATION ADD CONSTRAINT ORGANIZATION_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE(ID);

CREATE TABLE NETWORK (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    URL VARCHAR(256),
    PRIMARY KEY (ID)
);

CREATE TABLE IV_USER (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    PASSWORD VARCHAR(128) NOT NULL,
    IPHONE_ID VARCHAR(128),
    PRIMARY KEY (ID)
);

CREATE TABLE INTEGRATION (
    ID VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    NETWORK_ID VARCHAR(36) NOT NULL,
    USER_NAME VARCHAR(128) NOT NULL,
    PASSWORD VARCHAR(128),
    PRIMARY KEY (ID)
);

ALTER TABLE INTEGRATION ADD CONSTRAINT USER_INTEG_FK FOREIGN KEY (USER_ID) REFERENCES IV_USER(ID);
ALTER TABLE INTEGRATION ADD CONSTRAINT NETWORK_INTEG_FK FOREIGN KEY (NETWORK_ID) REFERENCES NETWORK(ID);

CREATE TABLE TIMEFRAME (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    BUCKET NUMERIC(30) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE DISTANCE (
    ID VARCHAR(36) NOT NULL,
    BUCKET NUMERIC(4) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FILTER (
    ID VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    LATITUDE VARCHAR(128),
    LONGITUDE VARCHAR(128),
    TIMEFRAME_ID VARCHAR(36),
    DISTANCE_ID VARCHAR(36),
    PRIMARY KEY (ID)
);

ALTER TABLE FILTER ADD CONSTRAINT FILTER_USER_FK FOREIGN KEY (USER_ID) REFERENCES IV_USER(ID);
ALTER TABLE FILTER ADD CONSTRAINT FILTER_TIMEFRAME_FK FOREIGN KEY (TIMEFRAME_ID) REFERENCES TIMEFRAME(ID);
ALTER TABLE FILTER ADD CONSTRAINT FILTER_DISTANCE_FK FOREIGN KEY (DISTANCE_ID) REFERENCES DISTANCE(ID);

CREATE TABLE FILTER_INTEREST_AREA (
    FILTER_ID VARCHAR(36) NOT NULL,
    INTEREST_AREA_ID VARCHAR(36) NOT NULL
);

ALTER TABLE FILTER_INTEREST_AREA ADD CONSTRAINT FIA_INTEREST_AREA_FK FOREIGN KEY (INTEREST_AREA_ID) REFERENCES INTEREST_AREA(ID);
ALTER TABLE FILTER_INTEREST_AREA ADD CONSTRAINT FIA_FILTER_FK FOREIGN KEY (FILTER_ID) REFERENCES FILTER(ID);

CREATE TABLE FILTER_ORGANIZATION_TYPE (
    FILTER_ID VARCHAR(36) NOT NULL,
    ORGANIZATION_TYPE_ID VARCHAR(36) NOT NULL
);

ALTER TABLE FILTER_ORGANIZATION_TYPE ADD CONSTRAINT FOT_FILTER_FK FOREIGN KEY (FILTER_ID) REFERENCES FILTER(ID);
ALTER TABLE FILTER_ORGANIZATION_TYPE ADD CONSTRAINT FOT_ORGANIZATION_TYPE_FK FOREIGN KEY (ORGANIZATION_TYPE_ID) REFERENCES ORGANIZATION_TYPE(ID);

CREATE TABLE SOURCE_INTEREST_MAP (
    ID VARCHAR(36) NOT NULL,
    SOURCE_ID VARCHAR(36) NOT NULL,
    SOURCE_KEY VARCHAR(128) NOT NULL,
    INTEREST_AREA_ID VARCHAR(36) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE SOURCE_INTEREST_MAP ADD CONSTRAINT SIM_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE(ID);
ALTER TABLE SOURCE_INTEREST_MAP ADD CONSTRAINT SIM_INTEREST_AREA_FK FOREIGN KEY (INTEREST_AREA_ID) REFERENCES INTEREST_AREA(ID);

CREATE TABLE SOURCE_ORG_TYPE_MAP (
    ID VARCHAR(36) NOT NULL,
    SOURCE_ID VARCHAR(36) NOT NULL,
    SOURCE_KEY VARCHAR(128) NOT NULL,
    ORGANIZATION_TYPE_ID VARCHAR(36) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE SOURCE_ORG_TYPE_MAP ADD CONSTRAINT SOTM_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE(ID);
ALTER TABLE SOURCE_ORG_TYPE_MAP ADD CONSTRAINT SOTM_ORG_TYPE_FK FOREIGN KEY (ORGANIZATION_TYPE_ID) REFERENCES ORGANIZATION_TYPE(ID);
