USE ivolunteer;

CREATE TABLE EVENTS (
	ID VARCHAR(36) NOT NULL,
	TITLE VARCHAR(256) NOT NULL,
    DESCRIPTION VARCHAR(1024) NOT NULL,
	TIMESTAMP TIMESTAMP NOT NULL,
    DURATION NUMERIC(3),
	LOCATION VARCHAR(512),
	LATITUDE VARCHAR(128),
	LONGITUDE VARCHAR(128),
	CONTACT VARCHAR(256),
	URL VARCHAR(256),
    STREET VARCHAR(256),
    CITY VARCHAR(256),
    STATE VARCHAR(2),
    ZIP VARCHAR(16),
	PHONE VARCHAR(64),
	EMAIL VARCHAR(256),
	ORGANIZATION_ID VARCHAR(36),
    SOURCE_ID VARCHAR(36),
    SOURCE_KEY VARCHAR(128),
    SOURCE_URL VARCHAR(256),
	PRIMARY KEY (ID)
);

CREATE TABLE ORGANIZATIONS (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    PHONE VARCHAR(64),
    EMAIL VARCHAR(512),
    URL VARCHAR(256),
    STREET VARCHAR(256),
    CITY VARCHAR(256),
    STATE VARCHAR(2),
    ZIP VARCHAR(16),
    ORGANIZATION_TYPE_ID VARCHAR(36),
    SOURCE_ID VARCHAR(36),
    SOURCE_KEY VARCHAR(128),
    SOURCE_URL VARCHAR(256),
    PRIMARY KEY (ID)
);

ALTER TABLE EVENTS ADD CONSTRAINT EVENTS_ORGANIZATIONS_FK FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATIONS(ID);

CREATE TABLE ORGANIZATION_TYPES (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(128),
    PRIMARY KEY (ID)
);

ALTER TABLE ORGANIZATIONS ADD CONSTRAINT ORGANIZATION_TYPE_FK FOREIGN KEY (ORGANIZATION_TYPE_ID) REFERENCES ORGANIZATION_TYPES(ID);

CREATE TABLE INTEREST_AREAS (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(128),
    PRIMARY KEY (ID)
);

CREATE TABLE EVENT_INTEREST_AREAS (
    INTEREST_AREA_ID VARCHAR(36) NOT NULL,
    EVENT_ID VARCHAR(36) NOT NULL
);

ALTER TABLE EVENT_INTEREST_AREAS ADD CONSTRAINT EIA_INTEREST_AREA_FK FOREIGN KEY (INTEREST_AREA_ID) REFERENCES INTEREST_AREAS(ID);
ALTER TABLE EVENT_INTEREST_AREAS ADD CONSTRAINT EIA_EVENTS_FK FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID);

CREATE TABLE ORGANIZATION_INTEREST_AREAS (
    INTEREST_AREA_ID VARCHAR(36) NOT NULL,
    ORGANIZATION_ID VARCHAR(36) NOT NULL
);

ALTER TABLE ORGANIZATION_INTEREST_AREAS ADD CONSTRAINT OIA_INTEREST_AREA_FK FOREIGN KEY (INTEREST_AREA_ID) REFERENCES INTEREST_AREAS(ID);
ALTER TABLE ORGANIZATION_INTEREST_AREAS ADD CONSTRAINT OIA_EVENTS_FK FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATIONS(ID);

CREATE TABLE SOURCES (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(128),
    ETL_CLASS VARCHAR(128),
    PRIMARY KEY (ID)
);

ALTER TABLE EVENTS ADD CONSTRAINT EVENTS_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCES(ID);
ALTER TABLE ORGANIZATIONS ADD CONSTRAINT ORGANIZATION_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCES(ID);
