#define MAX_X 320
#define MAX_Y 416
#define CENTER_X 160
#define CENTER_Y 208
#define KIOSK_MAP_VIEW_PORTRAIT_FRAME_RECT CGRectMake(0,0,320,366)

#define KIOSK_MAP_MARKER_FRAME_ANIMATE_RECT(x) CGRectMake(x, -30, 35, 36);
#define KIOSK_MAP_MARKER_FRAME_NO_ANIMATE_RECT(x,y) CGRectMake(x, y, 35, 36);
#define MARKER_DICT_BUTTON 0
#define MARKER_DICT_LAT 1
#define MARKER_DICT_LNG 2
#define MARKER_DICT_X 3
#define MARKER_DICT_Y 4
#define MARKER_INVISIBLE_BUTTON 5
#define CENTER_OFFSET_MARKER_RELOAD_THRESHOLD 150
#define MARKER_ICON_X_OFFSET -15.0
#define MARKER_ICON_Y_OFFSET -35.0